# Generated by Django 5.2.11 on 2026-03-18 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("videos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FocusSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "planned_duration",
                    models.IntegerField(
                        default=1800, help_text="Planned session duration in seconds"
                    ),
                ),
                (
                    "actual_duration",
                    models.IntegerField(
                        default=0, help_text="Actual watch time in seconds"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        default=0, help_text="Deprecated: use actual_duration"
                    ),
                ),
                (
                    "distraction_count",
                    models.IntegerField(
                        default=0, help_text="Times user left focus mode"
                    ),
                ),
                (
                    "pause_count",
                    models.IntegerField(default=0, help_text="Number of pauses"),
                ),
                (
                    "tab_switches",
                    models.IntegerField(
                        default=0, help_text="External tab switches detected"
                    ),
                ),
                (
                    "focus_score",
                    models.FloatField(
                        default=0.0, help_text="Quality of focus during session"
                    ),
                ),
                ("is_fullscreen", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("points_earned", models.IntegerField(default=0)),
                ("streak_maintained", models.BooleanField(default=True)),
                (
                    "topic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="focus_sessions",
                        to="courses.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_sessions",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Focus Session",
                "verbose_name_plural": "Focus Sessions",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="StudyNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "timestamp_in_video",
                    models.IntegerField(default=0, help_text="Seconds into video"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="focus.focussession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Note",
                "verbose_name_plural": "Study Notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="focussession",
            index=models.Index(
                fields=["user", "-start_time"], name="focus_focus_user_id_4be625_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="focussession",
            index=models.Index(fields=["status"], name="focus_focus_status_945bb0_idx"),
        ),
        migrations.AddIndex(
            model_name="focussession",
            index=models.Index(
                fields=["completed"], name="focus_focus_complet_ffde61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studynote",
            index=models.Index(
                fields=["user", "-created_at"], name="focus_study_user_id_0c94bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studynote",
            index=models.Index(fields=["video"], name="focus_study_video_i_cbc2b9_idx"),
        ),
    ]
