# Generated by Django 5.2.12 on 2026-04-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("youtube_id", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=255)),
                ("score", models.FloatField(default=0)),
            ],
        ),
    ]
