# Generated by Django 5.2.11 on 2026-03-18 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "youtube_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("description", models.TextField(blank=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("channel_name", models.CharField(blank=True, max_length=200)),
                (
                    "channel_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                (
                    "relevance_score",
                    models.FloatField(default=0.0, help_text="0-100 keyword relevance"),
                ),
                (
                    "quality_score",
                    models.FloatField(default=0.0, help_text="0-100 based on metadata"),
                ),
                (
                    "engagement_score",
                    models.FloatField(default=0.0, help_text="0-100 likes/views ratio"),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        default=0.5, help_text="0-1 comment sentiment (NLP)"
                    ),
                ),
                (
                    "teaching_quality_score",
                    models.FloatField(
                        default=0.0, help_text="0-100 teaching effectiveness"
                    ),
                ),
                (
                    "ai_score",
                    models.FloatField(
                        db_index=True, default=0.0, help_text="Final AI ranking 0-100"
                    ),
                ),
                (
                    "rank_position",
                    models.IntegerField(
                        blank=True, help_text="Topic-specific ranking", null=True
                    ),
                ),
                (
                    "channel_authority",
                    models.FloatField(
                        default=0.0, help_text="0-100 channel credibility score"
                    ),
                ),
                ("is_verified_channel", models.BooleanField(default=False)),
                ("total_watch_count", models.IntegerField(default=0)),
                (
                    "avg_completion_rate",
                    models.FloatField(
                        default=0.0, help_text="Average % watched (0-100)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_metadata_update", models.DateTimeField(blank=True, null=True)),
                ("times_recommended", models.IntegerField(default=0)),
                ("times_watched", models.IntegerField(db_index=True, default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="courses.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "ordering": ["-ai_score", "-published_at"],
                "indexes": [
                    models.Index(
                        fields=["topic", "-ai_score"],
                        name="videos_vide_topic_i_d2617d_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-ai_score"],
                        name="videos_vide_is_acti_b0c38b_idx",
                    ),
                    models.Index(
                        fields=["channel_id"], name="videos_vide_channel_918466_idx"
                    ),
                    models.Index(
                        fields=["times_watched"], name="videos_vide_times_w_d4b80b_idx"
                    ),
                ],
            },
        ),
    ]
