# Generated by Django 5.2.11 on 2026-03-18 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_reason",
                    models.TextField(
                        blank=True, help_text="User's personal learning goal"
                    ),
                ),
                (
                    "consistency_score",
                    models.FloatField(
                        default=0.0, help_text="0-100 user consistency index"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk - Consistent"),
                            ("MEDIUM", "Medium Risk - Declining"),
                            ("HIGH", "High Risk - Needs Intervention"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                (
                    "total_watch_time",
                    models.IntegerField(
                        default=0, help_text="Total watch time in seconds"
                    ),
                ),
                (
                    "avg_session_duration",
                    models.IntegerField(
                        default=0, help_text="Average session duration in seconds"
                    ),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                (
                    "avg_video_length_preference",
                    models.IntegerField(
                        default=15, help_text="Preferred video length in minutes"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                        ],
                        default="BEGINNER",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "indexes": [
                    models.Index(
                        fields=["consistency_score"],
                        name="users_profi_consist_cb7ebb_idx",
                    ),
                    models.Index(
                        fields=["risk_level"], name="users_profi_risk_le_b31d59_idx"
                    ),
                    models.Index(
                        fields=["current_streak"], name="users_profi_current_1a0ec2_idx"
                    ),
                ],
            },
        ),
    ]
