# Generated by Django 5.2.11 on 2026-03-18 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("videos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("RANKING", "Video Ranking"),
                            ("RECOMMENDATION", "Recommendation Engine"),
                            ("SENTIMENT", "Sentiment Analysis"),
                            ("PREDICTION", "Focus Prediction"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("f1_score", models.FloatField()),
                ("training_samples", models.IntegerField()),
                ("training_date", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Model Performance",
                "verbose_name_plural": "Model Performance Records",
                "ordering": ["-training_date"],
                "unique_together": {("model_type", "version")},
            },
        ),
        migrations.CreateModel(
            name="UserPreferenceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_video_length",
                    models.IntegerField(default=10, help_text="Minutes"),
                ),
                (
                    "preferred_teaching_style",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "preferred_channels",
                    models.JSONField(
                        default=list, help_text="List of trusted channel IDs"
                    ),
                ),
                ("optimal_session_time", models.TimeField(blank=True, null=True)),
                (
                    "optimal_session_duration",
                    models.IntegerField(default=1800, help_text="Seconds"),
                ),
                (
                    "weights_json",
                    models.JSONField(
                        default=dict, help_text="ML model weights for personalization"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference_model",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference Model",
                "verbose_name_plural": "User Preference Models",
            },
        ),
        migrations.CreateModel(
            name="VideoRankingTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.IntegerField()),
                ("likes", models.IntegerField()),
                ("comments", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("upload_age_days", models.IntegerField()),
                ("channel_subscribers", models.IntegerField(default=0)),
                (
                    "user_rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("teaching_effectiveness", models.FloatField(default=0.0)),
                ("feedback_source", models.CharField(default="MANUAL", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_data",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Ranking Training",
                "verbose_name_plural": "Video Ranking Training Data",
                "ordering": ["-created_at"],
            },
        ),
    ]
