# Generated by Django 5.2.12 on 2026-04-06 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focus", "0002_alter_focussession_duration_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="focussession",
            name="session_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
