# Generated by Django 5.2.12 on 2026-04-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="score",
            new_name="ai_score",
        ),
        migrations.AddField(
            model_name="video",
            name="duration_minutes",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="video",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
