# Generated by Django 5.2.11 on 2026-03-18 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("videos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StreakTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("total_days_active", models.IntegerField(default=0)),
                ("streak_started_at", models.DateField(blank=True, null=True)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("total_points", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streaks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Streak Tracking",
                "verbose_name_plural": "Streak Trackings",
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_score",
                    models.FloatField(help_text="0-100 recommendation score"),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("CONTENT", "Content Match"),
                            ("BEHAVIOR", "Behavior-based"),
                            ("COLLABORATIVE", "Collaborative Filtering"),
                            ("TRENDING", "Trending in Topic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Why was this recommended?"),
                ),
                ("was_clicked", models.BooleanField(default=False)),
                ("was_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("interacted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Recommendation",
                "verbose_name_plural": "AI Recommendations",
                "ordering": ["-recommendation_score"],
                "indexes": [
                    models.Index(
                        fields=["user", "-recommendation_score"],
                        name="tracking_ai_user_id_33ef32_idx",
                    ),
                    models.Index(
                        fields=["was_clicked"], name="tracking_ai_was_cli_609edf_idx"
                    ),
                ],
                "unique_together": {("user", "video")},
            },
        ),
        migrations.CreateModel(
            name="CommentSentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_text", models.TextField()),
                ("author", models.CharField(blank=True, max_length=200)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "Positive"),
                            ("NEUTRAL", "Neutral"),
                            ("NEGATIVE", "Negative"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(help_text="0-1 positive score from NLP"),
                ),
                (
                    "teaching_quality",
                    models.BooleanField(
                        default=False, help_text="Indicates teaching quality"
                    ),
                ),
                (
                    "clarity_feedback",
                    models.BooleanField(
                        default=False, help_text="Mentions clarity/understanding"
                    ),
                ),
                (
                    "criticism",
                    models.BooleanField(
                        default=False, help_text="Constructive criticism"
                    ),
                ),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_sentiments",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment Sentiment",
                "verbose_name_plural": "Comment Sentiments",
                "indexes": [
                    models.Index(
                        fields=["video", "sentiment"],
                        name="tracking_co_video_i_10ced5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBehaviorMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, db_index=True)),
                (
                    "total_watch_time",
                    models.IntegerField(
                        default=0, help_text="Total watch time in seconds"
                    ),
                ),
                ("videos_watched", models.IntegerField(default=0)),
                ("videos_completed", models.IntegerField(default=0)),
                ("avg_completion_rate", models.FloatField(default=0.0)),
                ("session_count", models.IntegerField(default=0)),
                (
                    "avg_session_duration",
                    models.IntegerField(
                        default=0, help_text="Average session length in seconds"
                    ),
                ),
                ("max_session_duration", models.IntegerField(default=0)),
                (
                    "skip_ratio",
                    models.FloatField(default=0.0, help_text="0-1 skip behavior"),
                ),
                (
                    "pause_ratio",
                    models.FloatField(default=0.0, help_text="0-1 pause frequency"),
                ),
                (
                    "completion_quality",
                    models.FloatField(
                        default=0.0, help_text="0-1 completion quality score"
                    ),
                ),
                ("streak_maintained", models.BooleanField(default=False)),
                ("streak_points", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Behavior Metrics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="tracking_us_user_id_d755c9_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="WatchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watch_time",
                    models.IntegerField(help_text="Actual watch time in seconds"),
                ),
                (
                    "video_duration",
                    models.IntegerField(help_text="Total video duration in seconds"),
                ),
                (
                    "completion_rate",
                    models.FloatField(default=0.0, help_text="% of video watched"),
                ),
                (
                    "skip_count",
                    models.IntegerField(default=0, help_text="Number of times skipped"),
                ),
                (
                    "rewind_count",
                    models.IntegerField(default=0, help_text="Number of times rewound"),
                ),
                (
                    "playback_speed",
                    models.FloatField(default=1.0, help_text="Average playback speed"),
                ),
                (
                    "pauses",
                    models.IntegerField(default=0, help_text="Number of pauses"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="STARTED",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_records",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watch History",
                "verbose_name_plural": "Watch Histories",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-started_at"],
                        name="tracking_wa_user_id_29b0b0_idx",
                    ),
                    models.Index(
                        fields=["video", "user"], name="tracking_wa_video_i_463bc8_idx"
                    ),
                    models.Index(
                        fields=["status"], name="tracking_wa_status_0b3c66_idx"
                    ),
                ],
            },
        ),
    ]
